### ISSUE TITLE
Check solution for B2

### ISSUE THREAD

**Issue by austinhartzheim** [austinhartzheim/cs564-p2#1]
The solution for B2 only seems to be finding directors and actors with no last name. Is this expected?

Also, we will need to modify this query before submission to only return the `fname,lname` columns.

**Comment by rfugs** [comment]
Currently debugging; both views work correctly. If you use the final query and just do `director_movie.mid = `actor_movie.mid`, its good. If you add in `director_movie.lname = actor_movie.lname`, it works. Breaks upon adding first name.

**Comment by austinhartzheim** [comment]
This seems to be caused (at least partially) by leading spaces in the name. See [Piazza](https://piazza.com/class/isscjy3to1z3fx?cid=99). I'll look into it further, but the current query might be correct given that the professor only wants us to check for strict equality.
