### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by rfugs** [austinhartzheim/cs564-p2#4]
- ~~A1 returns exact output~~
- ~~A2 returns exact output~~
- ~~A3 returns the correct amount of tuples~~
- ~~A4 not executing: `No such column: isholiday`~~
- ~~A5 returns correct amount of tuples~~
- A6: NOT DONE
- ~~A7 no validation provided~~
- B1 Returns 165370 tuples, should be 273 tuples
- ~~B2 returns correct amount of tuples~~
- ~~B3 returns correct top 4~~
- ~~B4 returns correct output for 2005-2010~~
- ~~B5 returns 2000 as per expected output~~
- ~~B6 returns 521875 as per expected output~~

Moving: A1, A2, A3, A5, B1, B2, B3, B4, B5, B6 to validated part of project.

May be good: A7

Needs fixing: A2, A4

Not started: A6

**Comment by rfugs** [comment]
I cannot figure out how to complete A2. What is currently returned is the top 20 sales, normalized, by a given department for each week. I then need to add together all these normalized weekly sales where department is the same. Any suggestions?
Example: [cells in column B should be summed if they have the same value in column A](https://drive.google.com/open?id=0B8zjLn0O2-aEMURucnBBa2FiS2s)

**Comment by austinhartzheim** [comment]
I've also updated B1 so that it only returns 292 tuples (I was forgetting to account for year). I'm not sure where the last few extras are coming from.

**Comment by austinhartzheim** [comment]
I also finished A6.

I believe the only outstanding problem is that we are returning a few too many tuples for B1. Do you want to look at that? I've been unable to figure it out.

**Comment by rfugs** [comment]
There are 100 actors with 10 roles and 192 with more than 10 roles, giving us 292. What if an actor had 2 roles in the same movie? It should be for distinct movies, not roles.

**Comment by austinhartzheim** [comment]
Thanks for fixing that.

Are there any remaining issues? Would you like me to submit?

**Comment by rfugs** [comment]
Let's submit, everything is returning results that are matching up nicely with the provided answers.
